paruparuku-webapp/app/blueprints/multilingual/__init__.py
from app.blueprints.multilingual.routes import multilingual

paruparuku-webapp/app/blueprints/multilingual/routes.py
# IMPORT LIBRARIES
import io, os, datetime

from flask import Flask, render_template, request, redirect, url_for, Blueprint, g, current_app, abort
from PIL import Image
from base64 import b64encode
from werkzeug.utils import secure_filename

from app import app
from app.blueprints.multilingual.route_functions import pneumoniaDetection, allowed_file, is_an_xray_image

# BLUEPRINT SETUP
multilingual = Blueprint('multilingual', __name__,
                         template_folder='templates', url_prefix='/<lang_code>')

@multilingual.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', g.lang_code)

@multilingual.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

@multilingual.before_request
def before_request():
    if g.lang_code not in current_app.config['LANGUAGES']:
        adapter = app.url_map.bind('')

        try:
            endpoint, args = adapter.match(
                '/en' + request.full_path.rstrip('/ ?'))
            
            return redirect(url_for(endpoint, **args), 301)
        except:
            abort(404)

    dfl = request.url_rule.defaults
    if 'lang_code' in dfl:
        if dfl['lang_code'] != request.full_path.split('/')[1]:
            abort(404)


# SETUP MAIN WEB ROUTES
@multilingual.route('/')
def main():
    return render_template(
        'multilingual/index.html',
        lang_code = g.lang_code
        )

@multilingual.route('/sumber', defaults={'lang_code': 'id'})
@multilingual.route('/sources', defaults={'lang_code': 'en'})
@multilingual.route('/來源', defaults={'lang_code': 'zh'})
@multilingual.route('/情報源', defaults={'lang_code': 'ja'})
def sources():
    return render_template(
        "multilingual/sources.html",
        lang_code = g.lang_code
        )

@multilingual.route('/tentang-kami', defaults={'lang_code': 'id'})
@multilingual.route('/about-us', defaults={'lang_code': 'en'})
@multilingual.route('/關於我們', defaults={'lang_code': 'zh'})
@multilingual.route('/私たちについて', defaults={'lang_code': 'ja'})
def about_us():
    return render_template(
        "multilingual/about-us.html", 
        page_name="about_us",
        lang_code = g.lang_code
        )

@multilingual.route('/tujuan-kami', defaults={'lang_code': 'id'})
@multilingual.route('/our-objectives', defaults={'lang_code': 'en'})
@multilingual.route('/我們的目標', defaults={'lang_code': 'zh'})
@multilingual.route('/私たちの目的', defaults={'lang_code': 'ja'})
def our_objectives():
    return render_template(
        "multilingual/our-objectives.html",
        page_name="our_objectives",
        lang_code = g.lang_code
        )

@multilingual.route('/deteksi', defaults={'lang_code': 'id'}, methods=['POST', 'GET'])
@multilingual.route('/detection', defaults={'lang_code': 'en'}, methods=['POST', 'GET'])
@multilingual.route('/檢測', defaults={'lang_code': 'zh'}, methods=['POST', 'GET'])
@multilingual.route('/検出', defaults={'lang_code': 'ja'}, methods=['POST', 'GET'])
def detection():
    # HANDLE REQUEST
    if request.method == 'POST':
        # CHECK WHETHER THE REQUEST HAS THE DESIRED INPUT
        if 'user_image_input' not in request.files:
            return redirect(request.url)

        file = request.files['user_image_input']

        # CHECK IF IMAGE WAS UPLOADED
        if file.filename == '':
            return redirect(request.url)

        # CHECK IF FILE TYPE IS AN IMAGE
        if file and allowed_file(file.filename):
            filename = str(datetime.datetime.now()) + "_" + secure_filename(file.filename)
            
            # SAVING FILE
            COMBINED_PATH = os.path.join(app.config['OUTPUT_FOLDER'], filename)
            file.save(COMBINED_PATH)

            # TEMPORARY IMAGE
            img = Image.open(COMBINED_PATH)
            img = img.convert('RGB')
            data = io.BytesIO()
            img.save(data, "JPEG")

            encoded = b64encode(data.getvalue())
            temp_img = encoded.decode('utf-8')

            # DETECTION AND REMOVE IMAGE
            prediction_results, CAM_images = pneumoniaDetection(image_name = filename, path = COMBINED_PATH)            
            os.remove(COMBINED_PATH)

            # IF IT IS AN X-RAY
            if prediction_results is not False:
                return render_template(
                    "multilingual/result.html",
                    prediction_results = prediction_results, 
                    image_file = temp_img,
                    CAM_images = CAM_images,
                    lang_code = g.lang_code
                    )
            # IF IT'S NOT AN X-RAY
            else:
                return render_template(
                    "multilingual/not-x-ray-image.html",
                    image_file = temp_img,
                    lang_code = g.lang_code
                    )

    
    # JIKA FILE EXTENSION BUKAN IMAGE
    return render_template(
        "multilingual/wrong-extension.html",
        lang_code = g.lang_code
        )

@app.errorhandler(500)
def internal_server_error(e):
    return render_template(
        "multilingual/error500.html",
        lang_code = g.lang_code
        )

@app.errorhandler(404)
def page_not_found(e):
    return render_template(
        "multilingual/error404.html",
        )

paruparuku-webapp/app/blueprints/multilingual/templates/multilingual/about-us.html
{% extends "layout.html" %} {% block title %}{{ gettext('About Us') | safe}}{%
endblock %} {% block content%}

<section id="hero">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/about-us-team.png"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="An illustration of three people side by side in a browser tab that resembles a team"
                    width="700"
                    height="500"
                    loading="lazy"
                />
            </div>
            <div class="col-lg-6">
                <h1 class="display-6 fw-bold mb-3">
                    {{ gettext('About Us') | safe}}
                </h1>
                <p class="lead">
                    {{ gettext(' We are four college students called
                    <strong class="fw-semibold">"Team Pengacara"</strong> from
                    <a target="_blank" href="https://www.uib.ac.id/"
                        >Universitas Internasional Batam</a
                    >. <br /><br />
                    ParuParuKu is a Flask-based web application that was built
                    by our amazing team for detecting pneumonia from patient\'s
                    X-ray image.') | safe}}
                </p>
            </div>
        </div>
    </div>
</section>
<section id="book-list">
    <div class="container col-xxl-8 mb-4 px-4">
        <h1 class="display-6 fw-bold mb-3">
            {{ gettext('Team Member') | safe}}
        </h1>
        <div
            class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3"
        >
            <div class="col">
                <div class="card shadow-sm">
                    <img
                        class="bd-placeholder-img card-img-top hero-img"
                        src="/static/assets/jonathan.svg"
                        alt="An avatar of Jonathan"
                        width="100%"
                        height="225"
                    />
                    <div class="card-body">
                        <h4 class="card-text h5 fw-semibold">Jonathan</h4>
                        <p>2031016</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <img
                        class="bd-placeholder-img card-img-top hero-img"
                        src="/static/assets/henry.svg"
                        alt="An avatar of Henry"
                        width="100%"
                        height="225"
                    />
                    <div class="card-body">
                        <h4 class="card-text h5 fw-semibold">Henry</h4>
                        <p>2031119</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <img
                        class="bd-placeholder-img card-img-top hero-img"
                        src="/static/assets/marvin-christian.svg"
                        alt="An avatar of Marvin Christian"
                        width="100%"
                        height="225"
                    />
                    <div class="card-body">
                        <h4 class="card-text h5 fw-semibold">
                            Marvin Christian
                        </h4>
                        <p>2031140</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <img
                        class="bd-placeholder-img card-img-top hero-img"
                        src="/static/assets/nicky-nicholas.svg"
                        alt="An avatar of Nicky Nicholas"
                        width="100%"
                        height="225"
                    />
                    <div class="card-body">
                        <h4 class="card-text h5 fw-semibold">Nicky Nicholas</h4>
                        <p>2031160</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

paruparuku-webapp/app/blueprints/multilingual/templates/multilingual/error500.html
{% extends "layout.html" %} {% block title %}{{ gettext('Internal Server Error') | safe}}{% endblock %}
{% block content%}


    <section id="hero">
        <div class="container col-xxl-8 px-4 py-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 pt-5">
                <div class="col-10 col-sm-8 col-lg-6">
                    <img
                        src="/static/assets/500.svg"
                        class="d-block mx-lg-auto img-fluid hero-img"
                        alt="Link between server and computer was disconnected by a mini character."
                        width="700"
                        height="500"
                        loading="lazy"
                    />
                </div>
                <div class="col-lg-6">
                    <h1 class="display-6 fw-bold mb-3">
                        {{ gettext('Internal Server Error') | safe}}
                    </h1>
                    <p class="lead">
                        {{ gettext('Oops! Something went wrong.
                        <br />
                        This may be caused by server errors or misconfigurations and was unable to complete your request
                        <br /><br />
                        Try to refresh the page and feel free to
                        <a target="_blank" href="mailto:2031016.jonathan@uib.edu">contact us</a>
                        if the problem persists.') | safe}}
                    </p>
                    <a href="/" type="button" class="btn btn-primary">
                        {{ gettext('Return to Main Page') | safe}}
                    </a>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

paruparuku-webapp/app/blueprints/multilingual/templates/multilingual/index.html
{% extends "layout.html" %} {% block title %}{{ gettext('ParuParuKu') | safe}}{% endblock %} 

{% block content%}
<section id="hero">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/index-doctor-1.png"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="An illustration containing two doctors"
                    width="700"
                    height="500"
                    loading="lazy"
                />
            </div>
            <div class="col-lg-6">
                <h1 class="display-6 fw-bold mb-3">
                    {{ gettext('We are here to help with your concerns!') | safe
                    }}
                </h1>
                <p class="lead">
                    {{ gettext('ParuParuKu will help predict how likely
                    you are to be infected with pneumonia based on your X-ray
                    scan!') | safe }}
                </p>
                <form
                    autocomplete="off"
                    method="POST"
                    action="{{ url_for('multilingual.detection') }}"
                    enctype="multipart/form-data"
                >
                    <div class="input-group mb-3">
                        <input
                            type="file"
                            accept="image/png, image/jpeg, image/jpg"
                            name="user_image_input"
                            class="form-control"
                            id="user_image_input"
                            required`
                        />
                        <button
                            type="submit"
                            class="input-group-text btn btn-primary"
                            onclick="toggleUploadLoader()"
                        >
                            {{ gettext('Submit') | safe }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<section id="seputar-pneumonia" class="bg-even">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/index-phone-1.jpg"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="A hand holding and clicking a phone"
                    width="700"
                    height="500"
                    loading="lazy"
                />
                <p class="text-start text-lg-center text-secondary mt-2">
                    {{ gettext('Photo by
                    <a target="_blank"
                        href="https://unsplash.com/@nordwood?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                        >NordWood Themes</a
                    >
                    on
                    <a target="_blank"
                        href="https://unsplash.com/s/photos/nordwood-themes-phone?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                        >Unsplash</a
                    >
                    ') | safe }}
                </p>
            </div>
            <div class="col-lg-6">
                <h1 class="fw-bold mb-3">
                    {{ gettext('A photo is all you need!') | safe }}
                </h1>
                <p class="lead">
                    {{ gettext('We immediately predict your pneumonia diagnosis
                    result using our 3 types of machine learning models.') |
                    safe }}
                </p>
                <ol class="lead">
                    <li>DenseNet201</li>
                    <li>MobileNetV2</li>
                    <li>NASNetMobile</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section id="urgensi-pneumonia">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5 pt-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/index-doctor-2.jpg"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="Doctor with heart shaped stethoscope"
                    width="700"
                    height="500"
                    loading="lazy"
                />
                <p class="text-start text-lg-center text-secondary mt-2">
                    {{ gettext('Photo by
                    <a target="_blank"
                        href="https://unsplash.com/@pattybphoto?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                        >Patty Brito</a
                    >
                    on
                    <a target="_blank"
                        href="https://unsplash.com/s/photos/doctor?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                        >Unsplash</a
                    >
                    ') | safe }}
                </p>
            </div>
            <div class="col-lg-6">
                <h1 class="fw-bold mb-3">
                    {{ gettext('Don\'t know what to do next?') | safe }}
                </h1>
                <p class="lead">
                    {{ gettext('We can give research-based recommendations
                    depending on your diagnosis results.') | safe }}
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock%}

paruparuku-webapp/app/blueprints/multilingual/templates/multilingual/not-x-ray-image.html
{% extends "layout.html" %} {% block title %}{{ gettext('Not an X-ray Image') | safe}}{% endblock %} 

{% block content%}
<section id="hero">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="data:image/jpeg;base64,{{ image_file }}"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="User's image"
                    width="700"
                    height="500"
                    loading="lazy"
                />
            </div>
            <div class="col-lg-6">
                <h1 class="display-6 fw-bold mb-3">
                    {{ gettext('Not an X-ray Image') | safe
                    }}
                </h1>
                <p class="lead">
                    {{ gettext('We don\'t think your uploaded image is an X-ray image. Uploading images that have unusual angles or colors may cause this issue.
                    <br /><br />
                    Please refer to the example below and upload it again in the form below!') | safe }}
                </p>
                <form
                    autocomplete="off"
                    method="POST"
                    action="{{ url_for('multilingual.detection') }}"
                    enctype="multipart/form-data"
                >
                    <div class="input-group mb-3">
                        <input
                            type="file"
                            accept="image/png, image/jpeg, image/jpg"
                            name="user_image_input"
                            class="form-control"
                            id="user_image_input"
                            required`
                        />
                        <button
                            type="submit"
                            class="input-group-text btn btn-primary"
                            onclick="toggleUploadLoader()"
                        >
                            {{ gettext('Submit') | safe }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<section class="bg-even">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/not-x-ray-image-1.jpeg"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="X-ray image example"
                    width="700"
                    height="500"
                    loading="lazy"
                />
            </div>
            <div class="col-lg-6">
                <h1 class="fw-bold mb-3">
                    {{ gettext('What should you upload?') | safe }}
                </h1>
                <p class="lead">
                    {{ gettext('ParuParuKu only detects specific kinds of images, so it is best that you upload your images that are similar to this image.
                    <br /><br />
                    We recommend that you scan your images first, then convert it to a supported file extension such as .jpg .jpeg or .png.
                    ') |
                    safe }}
                </p>
            </div>
        </div>
    </div>
</section>

{% endblock%}

paruparuku-webapp/app/blueprints/multilingual/templates/multilingual/our-objectives.html
{% extends "layout.html" %} {% block title %} {{ gettext('Our Objectives') |
safe }} {% endblock %} {% block content%}

<section class="bg-even">
    <div class="container px-4 py-5 text-start d-flex-col">
        <h1 class="display-6 pt-5 fw-bold text-lg-center">
            {{ gettext('Our Objectives') | safe }}
        </h1>
        <div class="col-lg-6 mx-auto text-lg-center pb-5">
            <p class="lead text-lg-center">
                {{ gettext('is to provide users with
                <strong class="fw-semibold">early detection</strong>
                of pneumonia based on X-ray images!') | safe }}
            </p>
        </div>
    </div>
</section>
<section id="seputar-pneumonia">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/objectives-doctor-1.jpg"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="A doctor diagnosing an X-ray image"
                    width="700"
                    height="500"
                    loading="lazy"
                />
                <p class="text-start text-lg-center text-secondary mt-2">
                    {{ gettext(' Photo by
                    <a target="_blank"
                        href="https://www.alodokter.com/mengenal-macam-macam-pneumonia"
                        >dr. Irene Cindy Sunur</a
                    >
                    on
                    <a target="_blank"
                        href="https://www.alodokter.com/mengenal-macam-macam-pneumonia"
                        >Alodokter</a
                    >
                    ') | safe }}
                </p>
            </div>
            <div class="col-lg-6">
                <h1 class="fw-bold mb-3">
                    {{ gettext('About pneumonia') | safe }}
                </h1>
                <p class="lead">
                    {{ gettext('Pneumonia is an inflammation of the tissue in
                    lungs caused by infection. Pneumonia can cause mild to
                    severe symptoms, such as coughing, fever, nausea, wheezing,
                    shortness of breath, and chest pain.<br /><br />
                    Pneumonia is not only found in adults but also in
                    children.') | safe }}
                </p>
            </div>
        </div>
    </div>
</section>
<section id="urgensi-pneumonia" class="bg-even">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5 pt-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/objectives-doctor-2.jpg"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="Few doctors are checking on equipments"
                    width="700"
                    height="500"
                    loading="lazy"
                />
                <p class="text-start text-lg-center text-secondary mt-2">
                    {{ gettext('Photo by
                    <a target="_blank"
                        href="https://unsplash.com/@mio6556?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                        >Walter Otto</a
                    >
                    on
                    <a target="_blank"
                        href="https://unsplash.com/@mio6556?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
                        >Unsplash</a
                    >
                    ') | safe }}
                </p>
            </div>
            <div class="col-lg-6">
                <h1 class="fw-bold mb-3">
                    {{ gettext('Why should you use this ParuParuKu?') | safe }}
                </h1>
                <p class="lead">
                    {{ gettext('There are times when doctors aren\'t available to
                    make a diagnosis on recently performed X-ray scans.
                    <br /><br />So early diagnosis is needed to take further
                    action.') | safe }}
                </p>
            </div>
        </div>
    </div>
</section>
<section>
    <div
        class="mt-auto col-xxl-8 container d-flex-col flex-wrap justify-content-between align-items-center py-5 px-4"
    >
        <h1 class="display-6 fw-bold text-lg-center pt-5">
            {{ gettext('Which is why, we are ready to help!') | safe }}
        </h1>
        <div class="col-lg-6 mx-auto text-lg-center pb-5">
            <p class="lead text-lg-center">
                {{ gettext('ParuParuKu will help predict your pneumonia
                diagnosis result based on your X-ray scan.') | safe }}
            </p>
            <form
                autocomplete="off"
                method="POST"
                action="{{ url_for('multilingual.detection') }}"
                enctype="multipart/form-data"
            >
                <div class="input-group mb-3">
                    <input
                        type="file"
                        accept="image/png, image/jpeg, image/jpg"
                        name="user_image_input"
                        class="form-control"
                        id="user_image_input"
                        required`
                    />
                    <button
                        type="submit"
                        class="input-group-text btn btn-primary"
                        onclick="toggleUploadLoader()"
                    >
                        {{ gettext('Submit')| safe }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock %}

paruparuku-webapp/app/blueprints/multilingual/templates/multilingual/wrong-extension.html
{% extends "layout.html" %} {% block title %}{{ gettext('Wrong File Extension') | safe}}{% endblock %} 

{% block content%}
<section id="hero">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img
                    src="/static/assets/wrong-extension-1.png"
                    class="d-block mx-lg-auto img-fluid hero-img"
                    alt="An illustration that resebles confused person"
                    width="700"
                    height="500"
                    loading="lazy"
                />
            </div>
            <div class="col-lg-6">
                <h1 class="display-6 fw-bold mb-3">
                    {{ gettext('Wrong File Extension!') | safe
                    }}
                </h1>
                <p class="lead">
                    {{ gettext('We cannot process your request as we don\'t think this is the correct file extension. 
                    <br /><br />
                    Please upload an x-ray image with a .jpg, .jpeg, or .png extension!') | safe }}
                </p>
                <form
                    autocomplete="off"
                    method="POST"
                    action="{{ url_for('multilingual.detection') }}"
                    enctype="multipart/form-data"
                >
                    <div class="input-group mb-3">
                        <input
                            type="file"
                            accept="image/png, image/jpeg, image/jpg"
                            name="user_image_input"
                            class="form-control"
                            id="user_image_input"
                            required`
                        />
                        <button
                            type="submit"
                            class="input-group-text btn btn-primary"
                            onclick="toggleUploadLoader()"
                        >
                            {{ gettext('Submit') | safe }}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock%}